language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
  - '4'
before_script:
  - npm install -g bower
  - bower install
script:
  - xvfb-run npm test