language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
  - '4'
before_script:
  - npm install -g bower
  - bower install
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 5
script:
  - npm test