language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- '6'
- '4'
before_script:
- npm install -g bower
- bower install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
script:
- npm test
deploy:
  provider: npm
  email: "lets.email.rob@gmail.com"
  on:
    tags: true
  api_key:
    secure: H1MS92RKEv67t+RvxtT/3YQ80XV0ySNysGn7i1jqmz0hUX6v3Pgc0+tvoOIgN97SeC8BNQi/jQYyiIuLaKhqeyEqXL/Tvk/MSXxd4qNHDAHJ30wtxgWkfKWDXHIp20h6sEzo5FyAMW6RVceI8Jmi2hjz2lKLOtTTNxppYwuNQMUFhEmNQhXXORp0cLt1Mdc8USB48crSkkHk4RZR4o+hIvuqZoAG0/j8nOzum+Sd/6bVbZwJgLKZGuapi21LhC7W3Lcit4zrrWlB1aXG7c54RvDi1X2n+0J59gU7gv0olBO11ig9guZIPDT/8ZxTq4yYXact+zI8rMFRavlEY5o1aBrAGrfyrpYuMKv1AOuwGP5SjHYRHBhBX92Y5aAOb24SVHlaqgjwpocGqeKiInwSeJ4WKCsEB/gp3PiGJMYKIMYdNcq5KzzPQ14DaKIMXBX2WVrWNGEwMa4UjOH9qu8yD/cFNcCeJ34nY1YDx4lf9+9BkNtbEyziUrSXZvgNfKBgPUWwVvR+wWp/LBbO0O4DYYdbRxoPPVofE5YeV4Alqtk3msuUrx400p3jbad0I9THnM8QfsgEKUtElesS+jTKXkZXiRmA05QODDDBK46fGTkKTKBA9lzdDq2oslnhwev/RWJwM+Y96gZPiJGpmhe/vyRElES2Bmr5LeWSdezi/n0=
